import React, { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { format } from "date-fns";
import { useQuery } from "@tanstack/react-query";
import { getTaskById } from "@/services/taskService";
import { useAuth } from "@/hooks/useAuth";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { MapPin, Calendar, DollarSign, User, Clock } from "lucide-react";
import { calculateDistance } from "@/services/location/distance";
import BottomNav from "@/components/BottomNav";
import { useToast } from "@/hooks/use-toast";
